name: PeoplesRepublicofMovies
favicon: null
layout_spectrum: 0.047585790045559406
typography_spectrum: 0.9640037943609059
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6c0005'
    - '#000000'
    - '#ecedb8'
    - '#36340e'
    - '#d5876f'
  brandStrength: 1
  lightness: 0.8744779760017991
  saturation: 0.9837677371688187
  rhythmicContrast: 0.8493849523365498
purpose: []
